#!/usr/bin/env bash

## WIP!

BASE=$(readlink -f "$(dirname "$0")"/..)
. $BASE/dotfiles/lib
umask 0007

for f in $templatedotfiles ; do
	printf "TEMPLATE[%s] " $f.mustache
	if [ ! -e "$BASE/$f.mustache" ] ; then
		# file specified in config but does not exist in repo
		echo "Not in repo. Skipping."
		continue
	fi
	if [ -L "$HOME/.$f" ] || [ ! -e "$HOME/.$f" ] ; then
		# already a symlink or does not exist
		echo "$HOME/.$f -> $BASE/$f"
		link "$BASE/$f" "$HOME/.$f"
	elif [ -e "$HOME/.$f" ] && [ "$force" -eq 1 ] ; then
		# file exists, and we were told to symlink anyway
		echo "  Moving ~/.$f -> ~/.$f.backup ; Symlinking ~/.$f -> $BASE/$f"
		mv "$HOME/.$f" "$HOME/.$f.backup" && link "$BASE/$f" "$HOME/.$f"
	else
		echo "  Already exists and is not a symlink. Skipping."
	fi
done

