#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
if [ -f "$HOME/.Xmodmap" ] ; then
	xmodmap "$HOME/.Xmodmap"
fi

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

test -n "`which feh`" && feh --bg-scale $HOME/.fluxbox/backgrounds/darklight.jpg
test -n "`which gkrellm`" && gkrellm &

test -x "`which xautolock`" && test -x "`which slock`" && xautolock -time 10 -locker slock &

if [ "$(hostname)" == "zirzla" ] ; then
	test -n "`which synclient`" && synclient TouchpadOff=1
	test -n "`which nm-applet`" && nm-applet &
	test -n "`which volumeicon`" && volumeicon &
	test -n "`which notify-osd`" && notify-osd &
	test -x "$HOME/bin/brightd" && $HOME/bin/brightd -w 120 -b 1 -f -f -d
fi

test -x "`which redshift`" && redshift -l 40.8:-77.8 &

if [ -d /usr/share/fonts/artwiz-fonts ] ; then
        xset fp+ "/usr/share/fonts/artwiz-fonts/"
fi

# make capslock another control
setxkbmap -option "ctrl:nocaps"

# turn off terminal bell
xset -b

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/phalenor/.fluxbox/log"
