apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: krew
spec:
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    To list krew commands and to get help, run:
      $ kubectl krew
    For a full list of available plugins, run:
      $ kubectl krew search

    You can find documentation at https://sigs.k8s.io/krew.
  homepage: https://sigs.k8s.io/krew
  platforms:
  - bin: krew
    files:
    - from: ./krew-darwin_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 2491801fc5b7823ab97fe5e9b23a6b79cdc65cae36953127e0410d827c1b883d
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 2491801fc5b7823ab97fe5e9b23a6b79cdc65cae36953127e0410d827c1b883d
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_arm
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm
        os: linux
    sha256: 2491801fc5b7823ab97fe5e9b23a6b79cdc65cae36953127e0410d827c1b883d
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.tar.gz
  - bin: krew.exe
    files:
    - from: ./krew-windows_amd64.exe
      to: krew.exe
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 2491801fc5b7823ab97fe5e9b23a6b79cdc65cae36953127e0410d827c1b883d
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.tar.gz
  shortDescription: Package manager for kubectl plugins.
  version: v0.3.3
